site_name: InfoTechTutorials
site_url: https://infotechtutorials.ca/

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
#    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search
  - blogging


nav:
    - Home: index.md
    - Blog:
      - Welcome: blog\index.md
    - Homelab Projects:
      - Welcome: HomeLab/index.md
      - Windows Server: HomeLab/WinSrv.md
    - About: about.md