site_name: InfoTechTutorials
site_url: https://infotechtutorials.ca/

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
#    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight

  
plugins:
  - search
  - blogging

markdown_extensions:
  - pymdownx.superfences



nav:
    - Home: index.md
    - Blog:
      - Welcome: blog/index.md
      - Blog - Windows 10 Virtual Machine inside of VMWare ESXi: blog/posts/Win10-vmware.md
    - Homelab Projects:
      - Windows Server Projects:
        - Project Goals: HomeLab/Windows_Projects/Project_Goals.md
        - Overview: HomeLab/Windows_Projects/index.md
        - OPNsense Install: HomeLab/Windows_Projects/opnsense.md
        - Windows Server:
            - Windows Server Installation: HomeLab/Windows_Projects/Windows_Server_Install/WinSrvInstall.md
            - DC-01: HomeLab/Windows_Projects/dc-01.md
            - DC-02: HomeLab/Windows_Projects/dc-02.md
            - Active Directory Domain Services: HomeLab/Windows_Projects/Active_Directory.md
            - Active Directory Users and Computers: HomeLab/Windows_Projects/users_and_computers.md
      - Linux Projects:
        - Installing Debian 12: HomeLab/Linux_Projects/Debian_12.md
        - DHCP Project: HomeLab/Linux_Projects/dhcp.md
    - About: about.md